# Generated by Django 3.1.6 on 2021-03-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_booked', models.DateField(blank=True, null=True)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('players', models.IntegerField(null=True)),
                ('service', models.CharField(blank=True, choices=[('IN', 'Introduction To DnD'), ('OS', 'One Shot Adventure'), ('OC', 'Ongoing Campaign')], max_length=2, null=True)),
                ('location', models.CharField(choices=[('IRL', 'In Real Life'), ('ONL', 'Online')], default='ONL', max_length=3, null=True)),
                ('comment', models.EmailField(blank=True, max_length=254)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
