# Generated by Django 3.1.6 on 2021-03-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210302_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
