# Generated by Django 3.1.6 on 2021-03-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_email', models.EmailField(max_length=254, unique=True)),
                ('subscribed', models.BooleanField(default=True)),
            ],
        ),
    ]
